---
- name: Create a vulnerable struts application
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Ensure context is correct
      shell: kubectx eks

    - name: Create project for struts app
      shell: kubectl create ns devops

    - name: Create struts app on eks
      shell: kubectl apply -f files/struts-deployment.yml

    - name: Expose struts app on eks
      shell: kubectl expose deployment struts-app --type=LoadBalancer --name=struts-svc -n devops
