---
- name: Create a vulnerable struts application
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Rename kubectx context
      shell: >
        kubectx openshift=.
      ignore_errors: yes

    - name: Create project for struts app
      k8s:
        state: present
        src: files/devops-project.yml

    - name: Add cluster-admin to default service account
      shell: oc adm policy add-role-to-user cluster-admin -z default -n devops

    - name: Add hostaccess SCC to default service account
      shell: oc adm policy add-scc-to-user hostaccess -z default -n devops

    - name: Deploy struts app
      k8s:
        state: present
        src: files/ocp-struts-deployment.yml

    - name: Create struts service
      shell: oc get svc struts-app -n devops || oc expose deployment/struts-app --port 8080 -n devops

    - name: Create struts route
      shell: oc get route struts-app -n devops || oc expose svc struts-app -n devops

    - name: Store struts route
      shell: oc get route struts-app -n devops -o json | jq -r .spec.host
      register: struts_route
