kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
  name: struts-app
  namespace: devops
  labels:
    app: struts-app
    app.kubernetes.io/component: struts-app
    app.kubernetes.io/instance: struts-app
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: struts-app
  template:
    metadata:
      creationTimestamp: null
      labels:
        deployment: struts-app
    spec:
      containers:
        - name: struts-app
          image: quay.io/smileyfritz/struts-app:latest
          securityContext:
            capabilities:
              add:
                - SYS_ADMIN
                - NET_ADMIN
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: unix-socket
              mountPath: /var/run/crio/crio.sock
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
      volumes:
        - name: unix-socket
          hostPath:
            path: /var/run/crio/crio.sock
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
